apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-config-map
  labels:
    app: prod-web-app
data:
  APP_ENV: production
  LOG_LEVEL: INFO
  APP_PORT: "8080"

# ConfigMaps are used to externalize non-sensitive configuration and inject it into containers as environment variables or files.

# kubectl apply -f configmap.yaml
# kubectl get configmap
# kubectl describe configmap prod-config-map
